apiVersion: v1
kind: Service
metadata:
  namespace: eks-sample-app
  name: eks-sample-service-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: eks-sample-linux-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80